import React from "react";
import { Container, Row, Col, Image } from "react-bootstrap";
import { Link } from "react-router-dom";
const Footer = () => {
  const currentYear = new Date().getFullYear();
  return (
    <footer>
      <Container>
        <Row
          style={{
            alignItems: "center",
            justifyContent: "center",
            marginBottom: "20px",
          }}
        >
          <Image
            src={`https://m.facebook.com/favicon.ico?next=https%3A%2F%2Fm.facebook.com%2F%3Fwtsid%3Drdr_07Uzt4rdM1mphPctm&refsrc=deprecated&wtsid=rdr_07Uzt4rdM1mphPctm&_rdr`}
            //src={"/images/facebook.svg"}
            style={{ height: "25px", width: "50px" }}
          />
          <Image
            src={`https://static.cdninstagram.com/rsrc.php/v3/yR/r/lam-fZmwmvn.png`}
            // src={"/images/instagram.svg"}
            style={{ height: "25px", width: "50px" }}
          />
          <Image
            src={`https://www.linkedin.com/favicon.ico`}
            // src={"/images/linkedin-in.svg"}
            style={{ height: "25px", width: "50px" }}
          />
          <Image
            src={`https://www.tiktok.com/favicon.ico`}
            // src={"/images/tiktok.svg"}
            style={{ height: "25px", width: "50px" }}
          />
          <Image
            src={`https://twitter.com/favicon.ico`}
            //src={"/images/x-twitter.svg"}
            style={{ height: "25px", width: "50px" }}
          />
        </Row>
        <Row>
          <span style={{ fontSize: "12px" }}>
            <strong>Disclaimer</strong>: HealthChannel aims to provide the most
            updated, accurate, and objective information to our clients. This
            information may change from time to time. Some content may be
            compensated via third-party advertisers. Any health related
            information presented was generated by medical professionals, which
            Health Channel presents without warranty. The list of products
            presented via our search algorithms are not exhaustive.{" "}
          </span>
        </Row>
        <Row>
          <Col className="text-center py-3">
            <Image
              src={`/api/webimage/662e0e1813b90687ef7706b3`}
              //  src="../favicon.ico"
              style={{
                color: "green",
                height: "18px",
                width: "18px",
                marginBottom: "5px",
              }}
            />{" "}
            <span style={{ fontSize: "14px" }}>
              <strong>HealthChannel</strong> &copy; {currentYear}. All rights
              reserved. Use of this site constitutes acceptance of our{" "}
              <Link to={"/termsofuse"} style={{ color: "black" }}>
                Terms of Use
              </Link>{" "}
              and{" "}
              <Link to={"/privacypolicy"} style={{ color: "black" }}>
                Privacy Policy
              </Link>
              .
            </span>
          </Col>
        </Row>
      </Container>
    </footer>
  );
};

export default Footer;
